use lv_codegen::{CodeGen, Rusty};
use proc_macro2::TokenStream;
use quote::quote;
use std::env;
use std::fs::File;
use std::io::prelude::*;
use std::path::PathBuf;

fn main() {
    let out_path = PathBuf::from(env::var("OUT_DIR").unwrap());
    let rs = out_path.join("generated.rs");

    let source = lightvgl_sys::_bindgen_raw_src();

    let codegen = CodeGen::from(source).unwrap();
    let widgets_impl: Vec<TokenStream> = codegen
        .get_widgets()
        .iter()
        .flat_map(|w| w.code(&()))
        .collect();

    let code = quote! {
        use lightvgl_sys::*;
        #(#widgets_impl)*
    };

    let mut file = File::create(rs).unwrap();
    writeln!(
        file,
        "/* automatically generated by lvgl-codegen */\n{}",
        code
    )
    .unwrap();

    let widgets_path = out_path.join("widgets.rs");
    let widgets_impl: Vec<TokenStream> = codegen
        .get_widgets()
        .iter()
        .flat_map(|w| w.gen_impl())
        .collect();
    let widgets_code = quote! {
        #(#widgets_impl)*
    };
    let mut widgets_file = File::create(widgets_path).unwrap();
    writeln!(
        widgets_file,
        "/* automatically generated by lvgl-codegen */\n{}",
        widgets_code
    )
    .unwrap();
}
