use lv_codegen::{CodeGen, Rusty};
use proc_macro2::TokenStream;
use quote::quote;
use std::env;
use std::fs::File;
use std::io::prelude::*;
use std::path::PathBuf;
use std::process::Command;

fn main() {
    let out_path = PathBuf::from(env::var("OUT_DIR").unwrap());
    let rs = out_path.join("generated.rs");

    let source = lightvgl_sys::_bindgen_raw_src();

    let codegen = CodeGen::from(source).unwrap();
    let widgets_impl: Vec<TokenStream> = codegen
        .get_widgets()
        .iter()
        .flat_map(|w| w.code(&()))
        .collect();

    let code = quote! {
        use ::core::ptr::NonNull;
        use lightvgl_sys::*;

        #(#widgets_impl)*
    };

    let mut file = File::create(&rs).unwrap();
    writeln!(
        file,
        "/* automatically generated by lv_codegen */\n{}",
        code
    )
    .unwrap();

    rustfmt_path().map(|rustfmt_path| {
        Command::new(&rustfmt_path)
            .arg(&rs)
            .arg("--config")
            .arg("max_width=200")
            .spawn()
            .expect("rustfmt generated.rs was unsuccessful");
    });

    let widgets_path = out_path.join("widgets.rs");
    let widgets_impl: Vec<TokenStream> = codegen
        .get_widgets()
        .iter()
        .flat_map(|w| w.gen_impl())
        .collect();
    let widgets_code = quote! {
        #(#widgets_impl)*
    };
    let mut widgets_file = File::create(&widgets_path).unwrap();
    writeln!(
        widgets_file,
        "/* automatically generated by lv_codegen */\n{}",
        widgets_code
    )
    .unwrap();

    rustfmt_path().map(|rustfmt_path| {
        Command::new(&rustfmt_path)
            .arg(&widgets_path)
            .arg("--config")
            .arg("max_width=200")
            .spawn()
            .expect("rustfmt widgets.rs was unsuccessful");
    });
}

fn rustfmt_path() -> Option<PathBuf> {
    if let Ok(rustfmt) = env::var("RUSTFMT") {
        return Some(PathBuf::from(rustfmt));
    } else if let Ok(rustfmt) = which::which("rustfmt") {
        return Some(rustfmt);
    }
    return None;
}
